### ISSUE TITLE
[Scroll - OpenOasis] Implement unit tests

### ISSUE THREAD

**Issue by Elli610** [Cypher-Laboratory/EVM-Verifier#4]
Once #1, #2 and #3 are closed, we need you to add unit tests for each function

## Description
The unit tests should be written in javaScript in `test/test.js` and cover all possibilities for each function from `contracts/AliceRingToken.sol` and `contracts/VerifyRingSignature.sol`.

## Skills needed
- Solidity understanding
- JavaScript basic skills

## Hours needed
Expected working time: 1 to 2 hours

## What is expected
- Add unit tests for `contracts/AliceRingToken.sol`. We need you to test : 
    - approve should revert
    - getApproved should always revert
    - setApprovalForAll should always revert
    - isApprovedForAll should always revert
    - safeTransferFrom should always revert
    - transferFrom should always revert
    - mint should mint a SBT to msg.sender if the signature is valid, and the status is UNKNOWN, else revert
    - burn should burn the SBT if called by its owner, else revert
- Add unit tests for `contracts/VerifyRingSignature.sol` (don't test the cryptography, only the inputs / outputs). We need you to test the following three possibilities: 
    - Case where the signature length is one 
    - Case where the signature is valid 
    - Case where the signature is not valid
- One `test/test.js` file which contains all the unit tests

**Comment by LeJamon** [comment]
I think we can close it because we build and test the verifier previous week-end ?

**Comment by Elli610** [comment]
implemented https://github.com/ks-hackathon/evm-verifier/blob/main/contracts/ringSigVerifier.sol
